set -s set-clipboard on

set -g allow-rename on
set -g default-shell /bin/zsh
set -g default-terminal "screen-256color"
set -g mouse on
set -g set-titles on
set -g set-titles-string "#W - #H"
set -g update-environment \
  "SSH_AUTH_SOCK SSH_CLIENT SSH_CONNECTION SSH_TTY"

bind k kill-session

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
